services:

  xray:
    restart: unless-stopped
    build: xray/image
    env_file: .env
    volumes:
      - ./data/xray:/data
      - ./data/log/xray:/data/log
    ports:
      - ${XRAY_PORT}:443/tcp
    command: "run -config /data/xray.json"
    networks:
      - network1
    depends_on:
      - tor-windree
      - tor-kassberke
      - tor-yasha
      - tor-j

  tor-windree:
    restart: unless-stopped
    build: tor/image
    tmpfs:
      - /root/.tor:size=100663296 # ~46MB * 2
    env_file: .env
    volumes:
      - ./data/tor-windree:/data
    networks:
      - network1
    ports:
      - ${WINDREE_TOR_PORT}:9050/tcp
      - ${WINDREE_OR_PORT}:9001/tcp
    healthcheck:
      test: [ "CMD", "/entrypoint.sh", "healthcheck" ]
      start_period: ${HEATHCHECK_DELAY}
      interval: 2m
      timeout: 10s
      retries: 1

  tor-kassberke:
    restart: unless-stopped
    build: tor/image
    tmpfs:
      - /root/.tor:size=100663296 # ~46MB * 2
    env_file: .env
    volumes:
      - ./data/tor-kassberke:/data
    networks:
      - network1
    ports:
      - ${KASSBERKE_TOR_PORT}:9050/tcp
    healthcheck:
      test: [ "CMD", "/entrypoint.sh", "healthcheck" ]
      start_period: ${HEATHCHECK_DELAY}
      interval: 2m
      timeout: 10s
      retries: 1

  tor-yasha:
    restart: unless-stopped
    build: tor/image
    tmpfs:
      - /root/.tor:size=100663296 # ~46MB * 2
    env_file: .env
    volumes:
      - ./data/tor-yasha:/data
    networks:
      - network1
    ports:
      - ${YASHA_TOR_PORT}:9050/tcp
    healthcheck:
      test: [ "CMD", "/entrypoint.sh", "healthcheck" ]
      start_period: ${HEATHCHECK_DELAY}
      interval: 2m
      timeout: 10s
      retries: 1

  tor-j:
    restart: unless-stopped
    build: tor/image
    tmpfs:
      - /root/.tor:size=100663296 # ~46MB * 2
    env_file: .env
    environment:
      - TOR_EXIT_NODES="{us}"
    volumes:
      - ./data/tor-j:/data
    networks:
      - network1
    ports:
      - ${J_TOR_PORT}:9050/tcp
    healthcheck:
      test: [ "CMD", "/entrypoint.sh", "healthcheck" ]
      start_period: ${HEATHCHECK_DELAY}
      interval: 2m
      timeout: 10s
      retries: 1

  configuration-generator:
    restart: unless-stopped
    build: configuration-generator/image
    volumes:
      - ./data-xray:/data/template
      - ./data/xray:/data/configuration
    command: "--watch /data/ --format json /data/template/xray.json.j2 /data/configuration/data.json /data/configuration/xray.json"

networks:
  network1:
    enable_ipv6: true
    ipam:
      driver: default
      config:
        - subnet: ${SUBNET}
