services:
  tor:
    restart: unless-stopped
    build: tor/image
    env_file: .env
    volumes:
      - ./data/tor:/data
    networks:
      - network1
    healthcheck:
      test: [ "CMD", "/entrypoint.sh", "healthcheck" ]
      start_period: ${HEATHCHECK_DELAY}
      interval: 2m
      timeout: 10s
      retries: 1

  dante:
    restart: unless-stopped
    build: ./dante/image
    env_file: .env
    volumes:
      - ./data/logs/log.socket:/dev/log
    ports:
      - ${PORT}:1080
    networks:
      network1:
        driver_opts:
          com.docker.network.endpoint.ifname: eth@dante
    depends_on:
      # - tor
      rsyslog:
        condition: service_healthy

  # speedtest:
  #   restart: unless-stopped
  #   build: speedtest/image
  #   env_file: .env
  #   networks:
  #     - net

  rsyslog:
    build: ./rsyslog
    restart: "unless-stopped"
    volumes:
      - ./data/logs:/data
    healthcheck:
      test: [ "CMD-SHELL", "grep -q '00000000:0202' /proc/net/tcp || exit 1" ] #This checks the internal Linux kernel table to see if any process is listening on port 514 (hex 0202).
      interval: 5s
      timeout: 3s
      retries: 5
      start_period: 5s

networks:
  network1:
    enable_ipv6: true
    ipam:
      driver: default
      config:
        - subnet: ${SUBNET}
